### ISSUE TITLE
desdeo_problem.problem,objective line 667

### ISSUE THREAD

**Issue by ppouyaa** [industrial-optimization-group/desdeo-problem#27]
we need to add "return_std= True" to model.predict(decision_vector) to have the uncertainty information as well. otherwise, we get an error when we want to use this function. 
![issue1](https://user-images.githubusercontent.com/39522102/127295805-e254435e-6d5e-4cf4-8b14-a11087bae959.png)

**Comment by light-weaver** [comment]
No we should not. The way classes in desdeo-problem are implemented, they assume that all surrogate models have a predict method that returns **both** the predicted values and some measure of uncertainity. Hence the `return_std` parameter is redundant. 

In the `surrogatemodels` module, you can see how the sklearn classes (like `GaussianProcessRegressor`) have been modified to accomodate this.

https://github.com/industrial-optimization-group/desdeo-problem/blob/857585e74badf6cae4a0446aca9cd482e07f4e6f/desdeo_problem/surrogatemodels/SurrogateModels.py#L32
