### ISSUE TITLE
Create template for test problems

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/desdeo-problem#38]
Refactor the current DTLZ, ZDT and WFG problem formulations to set an example for future problems.

**Comment by gialmisi** [comment]
Implemented dummy_problem.py in desdeo-problem as an example.

See: https://github.com/industrial-optimization-group/desdeo-problem/blob/a3364f813cb7510d0373f11e70683dce3eb8bc86/desdeo_problem/testproblems/DummyProblem.py

Closing this issue for now.
