### ISSUE TITLE
This is the Vehicle Crashworthiness problem, not car-side impact problem. Rename the file and function for clarity.

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/desdeo-problem#70]
https://github.com/industrial-optimization-group/desdeo-problem/blob/bd9c2482d10c8850ee849a36c855da4f1a648ad0/desdeo_problem/testproblems/CarCrash.py#L7

**Comment by maaviixu** [comment]
Thanks, I'll do that!

**Comment by maaviixu** [comment]
Fixed in #72
