### ISSUE TITLE
Two tests not passing

### ISSUE THREAD

**Issue by gialmisi** [industrial-optimization-group/desdeo-problem#79]
The tests `test_evaluate_gaa` and `test_evaluate_multiple_clutch_brakes` are not passing. The tolerance of the comparison to the expected value should be fine tuned. We arrived to the conclusion with @maaviixu earlier, that the code is correct and the discrepancies in the current comparisons stem from floating point precision errors and updated code (i.e., the true value was originally computed with an older version of the referenced test problem).

The non-passing tests are located [here](https://github.com/industrial-optimization-group/desdeo-problem/blob/150ad2d44df159186b26c6dfac0df7fd7b9d5aa6/tests/test_gaa.py#L21) and [here](https://github.com/industrial-optimization-group/desdeo-problem/blob/150ad2d44df159186b26c6dfac0df7fd7b9d5aa6/tests/test_multiple_clutch_brakes.py#L21).

**Comment by gialmisi** [comment]
Still an issue in #82 

@maaviixu

**Comment by maaviixu** [comment]
Fixed in #84

**Comment by gialmisi** [comment]
Thanks!
